name: Lint

on:
  - push
  - pull_request

jobs:
  norminette:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          cache: pip
      - name: Install `norminette`
        run: python3 -m pip install norminette
      - uses: actions/checkout@v4
      - run: norminette
